apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-automation
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/flux-demo/image-automation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system