apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-demo-website-repository.yaml
  - flux-demo-website-policy-dev.yaml
  - flux-demo-website-policy-staging.yaml
  - flux-demo-website-policy-prod.yaml
  - image-update-automation.yaml